name: app_login_ui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_widget_from_html: ^0.15.0
  # flutter_riverpod: ^2.5.1
  go_router: ^14.1.4
  # riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  # riverpod_generator: ^2.4.0
  # build_runner: ^2.4.9
  # custom_lint: ^0.6.4
  # riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true